### ISSUE TITLE
Difference between webworker-promise and comlink

### ISSUE THREAD

**Issue by sedghi** [kwolfy/webworker-promise#22]
Hello, first of all, I want to express my gratitude for your open source repository. It has greatly enhanced the experience of working with workers.

Currently, I'm exploring options for incorporating a library that can improve the developer experience of workers for users of our apps and libraries. After some research, I have narrowed down my choices to your repository and comlink. However, I couldn't find a section in the readme that explains the differences between the two.

Would it be possible for you to provide some clarification on the distinctions between your repository and comlink? I appreciate your help. Thank you very much.

**Comment by kwolfy** [comment]
Hello.
Basically there really isn't much difference between them, but comlink is much more flexible and popular, so, I would recommend you to use it.

The only reason webworker-promise was created was because comlink didn't exist back then. Webworker-promise only still exists because a lot of people already use it and it would be bad of me to abandon the library, although I can't devote enough time to make quick fixes, much less improve

**Comment by kwolfy** [comment]
Thank you for your feedback, I marked webworker-promise as deprecated since comlink does look better and has reputable developers

**Comment by sedghi** [comment]
Thanks a lot for your answer

**Comment by sedghi** [comment]
@floryst FYI guys, since I know you use this
